# Particle Properties
elementary_charge: 1.602176634e-19 #C

e_mass_amu: 0.0005446623 # Units of proton mass 
e_mass_keV: 510998.95069 #eV/c^2
e_mass_kg: 9.1093837139e-31 # kg
e_Z: -1.602176634e-19 # Atomic number

p_mass_amu: 1 # Units of proton mass 
p_mass_keV: 938272000 #eV/c^2
p_mass_kg: 1.67262192e-27 # kg
p_Z: 1.602176634e-19 # Atomic number


time_plots_size: 0.08
time_plots_color: "blue"
time_plots_ylabel_fontsize: 10

drift_plots_width: 0.5
drift_plots_color: "red"
drift_plots_ylabel_fontsize: 20
drift_plots_xlabel_fontsize: 20

drift_scatter_size: 0.1
drift_scatter_color: "red"

contour_grid_density: 100
contour_levels_default: 15
contour_cmap: "plasma"

parabolas_color: "b"
parabolas_width: 0.6
dashed_color: "b"
dashed_width: 0.6

orbit_point_size: 7
orbit_point_marker: "o"
orbit_point_edge_color: "k"
orbit_point_face_color: "red"

torus2d_wall_color: "k"
torus2d_wall_size: 0.3
torus2d_orbit_color: "blue"
torus2d_orbit_size: 0.07

torus3d_wall_color: "cyan"
torus3d_wall_alpha: 0.3
torus3d_orbit_color: "red"
torus3d_orbit_alpha: 0.6
torus3d_orbit_size: .2

